services:
  api:
    build: .
    ports:
     - "8080:8080"
    env_file:
      - .env

  client-generator:
    build: .
    ports:
      - "5672:5672"
    command: uv run python -m src.workers.client_generator_worker
    env_file:
      - .env

